services:
  postgres:
    image: postgres:15
    container_name: cyberpulse_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - cyberpulse_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      retries: 5

  streamlit:
    image: python:3.11-slim
    container_name: cyberpulse_streamlit
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cyberpulse_net
    command:
      - bash
      - -c
      - "apt-get update -qq && apt-get install -y -qq default-libmysqlclient-dev pkg-config gcc && pip install -r requirements.txt psycopg2-binary spacy --quiet && python -m spacy download en_core_web_sm && streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0"

  airflow:
    image: apache/airflow:2.8.0
    container_name: cyberpulse_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__WEBSERVER__SECRET_KEY=cyberpulse_secret_key
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
    volumes:
      - ./pipelines:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./db:/opt/airflow/db
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cyberpulse_net
    command: bash -c "pip install dbt-postgres sqlalchemy pandas requests feedparser python-dotenv && airflow db init && airflow users create --username admin --password admin --firstname Kat --lastname Xelis --role Admin --email kat@cyberpulse.fr ; airflow webserver -p 8080 & airflow scheduler"

volumes:
  postgres_data:


networks:
  cyberpulse_net:
    driver: bridge
